apiVersion: v1
kind: Service
metadata:
  name: {{ include "pg.fullname" . }}
  labels:
    {{- include "pg.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.service.port }}
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "pg.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
    statefulset.kubernetes.io/pod-name: {{ include "pg.fullname" . }}-0
